//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace PropertyManagement1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Full_Contract
    {
        public int ID { get; set; }
        public string Full_Contract_Code { get; set; }
        [Required(ErrorMessage = "Tên Khách Hàng")]
        [StringLength(500, ErrorMessage = "Độ Dài Không Hợp Lệ", MinimumLength = 3)]
        public string Customer_Name { get; set; }
        [Display(Name = " Ngày Sinh"), Required]
        [StringLength(60, ErrorMessage = "Nhập đúng định dạng",MinimumLength = 3)]
        [DataType(DataType.Date)]
        public Nullable<int> Year_Of_Birth { get; set; }
        public string SSN { get; set; }
        [Required(ErrorMessage = "Địa Chỉ còn trống")]
        [StringLength(500, ErrorMessage = "Độ Dài Không Hợp Lệ", MinimumLength = 3)]
        public string Customer_Address { get; set; }
        public string Mobile { get; set; }
        public int Property_ID { get; set; }
        public Nullable<System.DateTime> Date_Of_Contract { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:c}")]

        [UIHint("Currency")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> Price { get; set; }

        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Remain { get; set; }
        public bool Status { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
